export const GET_COMPANIES = "GET_COMPANIES";
export const GET_WORKERS = "GET_WORKERS";
export const GET_ACTIVITIES = "GET_ACTIVITIES";
export const GET_EQUIPMENTS = "GET_EQUIPMENTS";
export const GET_ROLES = "GET_ROLES";
export const GET_ACTIVITIES_WORKERS = "GET_ACTIVITIES_WORKERS";